# Generated by Django 5.2.7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kursus', models.CharField(max_length=200, verbose_name='Kursus')),
                ('sted', models.CharField(max_length=100, verbose_name='Sted')),
                ('arrangor', models.CharField(max_length=100, verbose_name='Arrangør')),
                ('pris', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pris')),
                ('file', models.FileField(blank=True, null=True, upload_to='kursus_files/{instance.user.id}/{filename}', verbose_name='Fil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kursus_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kursus',
                'verbose_name_plural': 'Kursus Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
