# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_kursus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kursus',
            name='file',
            field=models.FileField(upload_to='kursus_files/{instance.user.id}/{filename}', verbose_name='Fil'),
        ),
    ]
