# Generated by Django 4.2.7 on 2025-10-14 19:22

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_fix_bilagsnr_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kursus',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=profiles.models.kursus_file_upload_path, verbose_name='Fil'),
        ),
    ]
