# Generated by Django 4.2.7 on 2025-10-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_kursus_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kursus',
            name='file',
        ),
        migrations.AddField(
            model_name='kursus',
            name='file_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='Fil Data'),
        ),
        migrations.AddField(
            model_name='kursus',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fil Navn'),
        ),
        migrations.AddField(
            model_name='kursus',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fil Størrelse'),
        ),
        migrations.AddField(
            model_name='kursus',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fil Type'),
        ),
    ]
